/**
 * take from plugin:@stylistic/disable-legacy
 * @version 2.3.0
 */
module.exports = {
  'array-bracket-newline': 0,
  'array-bracket-spacing': 0,
  'array-element-newline': 0,
  'arrow-parens': 0,
  'arrow-spacing': 0,
  'block-spacing': 0,
  'brace-style': 0,
  // 'callback-return': 0,
  'comma-dangle': 0,
  'comma-spacing': 0,
  'comma-style': 0,
  'computed-property-spacing': 0,
  'dot-location': 0,
  'eol-last': 0,
  'func-call-spacing': 0,
  'function-call-argument-newline': 0,
  'function-paren-newline': 0,
  'generator-star-spacing': 0,
  // 'global-require': 0,
  // 'handle-callback-err': 0,
  'implicit-arrow-linebreak': 0,
  'indent': 0,
  'jsx-quotes': 0,
  'key-spacing': 0,
  'keyword-spacing': 0,
  'linebreak-style': 0,
  'lines-around-comment': 0,
  'lines-between-class-members': 0,
  'max-len': 0,
  'max-statements-per-line': 0,
  'multiline-ternary': 0,
  'new-parens': 0,
  'newline-per-chained-call': 0,
  // 'no-buffer-constructor ': 0,
  'no-confusing-arrow': 0,
  'no-extra-parens': 0,
  'no-extra-semi': 0,
  'no-floating-decimal': 0,
  'no-mixed-operators': 0,
  // 'no-mixed-requires ': 0,
  'no-mixed-spaces-and-tabs': 0,
  'no-multi-spaces': 0,
  'no-multiple-empty-lines': 0,
  // 'no-new-require': 0,
  // 'no-path-concat': 0,
  // 'no-process-env': 0,
  // 'no-process-exit': 0,
  // 'no-restricted-modules': 0,
  // 'no-return-await': 0,
  // 'no-sync': 0,
  'no-tabs': 0,
  'no-trailing-spaces': 0,
  'no-whitespace-before-property': 0,
  'nonblock-statement-body-position': 0,
  'object-curly-newline': 0,
  'object-curly-spacing': 0,
  'object-property-newline': 0,
  'one-var-declaration-per-line': 0,
  'operator-linebreak': 0,
  'padded-blocks': 0,
  'padding-line-between-statements': 0,
  // 'prefer-reflect': 0,
  'quote-props': 0,
  'quotes': 0,
  // 'require-jsdoc': 0,
  'rest-spread-spacing': 0,
  'semi': 0,
  'semi-spacing': 0,
  'semi-style': 0,
  'space-before-blocks': 0,
  'space-before-function-paren': 0,
  'space-in-parens': 0,
  'space-infix-ops': 0,
  'space-unary-ops': 0,
  'spaced-comment': 0,
  'switch-colon-spacing': 0,
  'template-curly-spacing': 0,
  'template-tag-spacing': 0,
  // 'valid-jsdoc': 0,
  'wrap-iife': 0,
  'wrap-regex': 0,
  'yield-star-spacing': 0,
  '@typescript-eslint/block-spacing': 0,
  '@typescript-eslint/brace-style': 0,
  '@typescript-eslint/comma-dangle': 0,
  '@typescript-eslint/comma-spacing': 0,
  '@typescript-eslint/func-call-spacing': 0,
  '@typescript-eslint/indent': 0,
  '@typescript-eslint/key-spacing': 0,
  '@typescript-eslint/keyword-spacing': 0,
  '@typescript-eslint/lines-around-comment': 0,
  '@typescript-eslint/lines-between-class-members': 0,
  '@typescript-eslint/member-delimiter-style': 0,
  '@typescript-eslint/no-extra-parens': 0,
  '@typescript-eslint/no-extra-semi': 0,
  '@typescript-eslint/object-curly-spacing': 0,
  '@typescript-eslint/padding-line-between-statements': 0,
  '@typescript-eslint/quotes': 0,
  '@typescript-eslint/semi': 0,
  '@typescript-eslint/space-before-blocks': 0,
  '@typescript-eslint/space-before-function-paren': 0,
  '@typescript-eslint/space-infix-ops': 0,
  '@typescript-eslint/type-annotation-spacing': 0,
  'react/jsx-child-element-spacing': 0,
  'react/jsx-closing-bracket-location': 0,
  'react/jsx-closing-tag-location': 0,
  'react/jsx-curly-brace-presence': 0,
  'react/jsx-curly-newline': 0,
  'react/jsx-curly-spacing': 0,
  'react/jsx-equals-spacing': 0,
  'react/jsx-first-prop-new-line': 0,
  'react/jsx-indent': 0,
  'react/jsx-indent-props': 0,
  'react/jsx-max-props-per-line': 0,
  'react/jsx-newline': 0,
  'react/jsx-one-expression-per-line': 0,
  'react/jsx-props-no-multi-spaces': 0,
  'react/jsx-self-closing-comp': 0,
  'react/jsx-sort-props': 0,
  'react/jsx-tag-spacing': 0,
  'react/jsx-wrap-multilines': 0,
  // ---------------------------------
  'id-blacklist': 0, // replaced by id-denylist
  'lines-around-directive': 0, // replaced by padding-line-between-statements
  'newline-after-var': 0, // replaced by padding-line-between-statements
  'newline-before-return': 0, // replaced by padding-line-between-statements
  'no-catch-shadow': 0, // replaced by no-shadow
  'no-native-reassign': 0, // replaced by no-global-assign
  'no-negated-in-lhs': 0, // replaced by no-unsafe-negation
  'no-new-object': 0, // replaced by no-object-constructor
  'no-spaced-func': 0, // replaced by func-call-spacing
};
