/**
 * @version 48.0.1
 * @see https://github.com/sindresorhus/eslint-plugin-unicorn#rules
 */
module.exports = {
  'unicorn/better-regex': 2,
  'unicorn/escape-case': 2,
  'unicorn/explicit-length-check': 2,
  // 'unicorn/new-for-builtins': 2, // `no-new-native-nonconstructor` + `no-new-wrappers` + `no-new-symbol`
  'unicorn/no-array-method-this-argument': 2,
  'unicorn/no-array-push-push': 2,
  'unicorn/no-await-expression-member': 2,
  'unicorn/no-console-spaces': 2,
  'unicorn/no-for-loop': 2,
  'unicorn/no-hex-escape': 2,
  'unicorn/no-instanceof-array': 2,
  'unicorn/no-invalid-remove-event-listener': 2,
  'unicorn/no-lonely-if': 2,
  'unicorn/no-new-array': 2,
  'unicorn/no-new-buffer': 2,
  'unicorn/no-static-only-class': 2,
  'unicorn/no-thenable': 2,
  'unicorn/no-unnecessary-await': 2,
  // 'unicorn/no-unnecessary-polyfills': [2, { targets: [] / { node: 'current' } }],
  'unicorn/no-useless-spread': 2,
  'unicorn/no-useless-undefined': 2,
  'unicorn/number-literal-case': 2,
  'unicorn/prefer-array-find': 2,
  'unicorn/prefer-array-flat-map': 2,
  'unicorn/prefer-array-index-of': 2,
  'unicorn/prefer-array-some': 2,
  'unicorn/prefer-default-parameters': 2,
  'unicorn/prefer-dom-node-dataset': 2,
  'unicorn/prefer-dom-node-text-content': 2,
  // 'unicorn/prefer-math-trunc': 2,
  'unicorn/prefer-negative-index': 2,
  'unicorn/prefer-number-properties': 2,
  // 'unicorn/prefer-optional-catch-binding': 2,
  'unicorn/prefer-prototype-methods': 2,
  'unicorn/prefer-query-selector': 2,
  'unicorn/prefer-set-has': 2,
  'unicorn/prefer-set-size': 2,
  'unicorn/prefer-string-slice': 2,
  'unicorn/prefer-string-starts-ends-with': 2,
  'unicorn/prefer-string-trim-start-end': 2,
  'unicorn/require-array-join-separator': 2,
  'unicorn/require-number-to-fixed-digits-argument': 2,
  'unicorn/text-encoding-identifier-case': 2,
  'unicorn/throw-new-error': 2,
};
